/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "Paralelo_SerialSynth.v:1" *)
module Paralelo_SerialSynth(data_in, clk_4f, clk_32f, valid_in, reset, data_out);
  (* src = "Paralelo_SerialSynth.v:25" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  (* src = "Paralelo_SerialSynth.v:3" *)
  input clk_32f;
  (* src = "Paralelo_SerialSynth.v:3" *)
  input clk_4f;
  (* src = "Paralelo_SerialSynth.v:6" *)
  wire [7:0] contador;
  (* src = "Paralelo_SerialSynth.v:2" *)
  input [7:0] data_in;
  (* src = "Paralelo_SerialSynth.v:4" *)
  output data_out;
  (* src = "Paralelo_SerialSynth.v:3" *)
  input reset;
  (* src = "Paralelo_SerialSynth.v:3" *)
  input valid_in;
  NOT _068_ (
    .A(contador[2]),
    .Y(_004_)
  );
  NOT _069_ (
    .A(contador[3]),
    .Y(_005_)
  );
  NOT _070_ (
    .A(contador[4]),
    .Y(_006_)
  );
  NOT _071_ (
    .A(contador[5]),
    .Y(_007_)
  );
  NOT _072_ (
    .A(contador[6]),
    .Y(_008_)
  );
  NOT _073_ (
    .A(contador[7]),
    .Y(_009_)
  );
  NOT _074_ (
    .A(reset),
    .Y(_010_)
  );
  NOT _075_ (
    .A(valid_in),
    .Y(_011_)
  );
  NOT _076_ (
    .A(contador[1]),
    .Y(_012_)
  );
  NOT _077_ (
    .A(data_in[2]),
    .Y(_013_)
  );
  NOT _078_ (
    .A(data_in[7]),
    .Y(_014_)
  );
  NAND _079_ (
    .A(reset),
    .B(contador[0]),
    .Y(_000_[0])
  );
  NOR _080_ (
    .A(contador[0]),
    .B(contador[1]),
    .Y(_015_)
  );
  NAND _081_ (
    .A(contador[0]),
    .B(contador[1]),
    .Y(_016_)
  );
  NAND _082_ (
    .A(reset),
    .B(_016_),
    .Y(_017_)
  );
  NOR _083_ (
    .A(_015_),
    .B(_017_),
    .Y(_018_)
  );
  NOT _084_ (
    .A(_018_),
    .Y(_000_[1])
  );
  NAND _085_ (
    .A(_004_),
    .B(_012_),
    .Y(_019_)
  );
  NOR _086_ (
    .A(contador[0]),
    .B(_019_),
    .Y(_020_)
  );
  NOT _087_ (
    .A(_020_),
    .Y(_021_)
  );
  NOR _088_ (
    .A(_004_),
    .B(_015_),
    .Y(_022_)
  );
  NOR _089_ (
    .A(_010_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _090_ (
    .A(_021_),
    .B(_023_),
    .Y(_000_[2])
  );
  NOR _091_ (
    .A(contador[3]),
    .B(_021_),
    .Y(_024_)
  );
  NAND _092_ (
    .A(_005_),
    .B(_020_),
    .Y(_025_)
  );
  NOR _093_ (
    .A(_005_),
    .B(_020_),
    .Y(_026_)
  );
  NOR _094_ (
    .A(_024_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _095_ (
    .A(contador[4]),
    .B(_025_),
    .Y(_028_)
  );
  NOT _096_ (
    .A(_028_),
    .Y(_029_)
  );
  NOR _097_ (
    .A(contador[5]),
    .B(_029_),
    .Y(_030_)
  );
  NAND _098_ (
    .A(_007_),
    .B(_028_),
    .Y(_031_)
  );
  NOR _099_ (
    .A(contador[6]),
    .B(_031_),
    .Y(_032_)
  );
  NAND _100_ (
    .A(_009_),
    .B(_032_),
    .Y(_033_)
  );
  NAND _101_ (
    .A(contador[7]),
    .B(reset),
    .Y(_034_)
  );
  NAND _102_ (
    .A(reset),
    .B(_033_),
    .Y(_035_)
  );
  NOR _103_ (
    .A(_027_),
    .B(_035_),
    .Y(_000_[3])
  );
  NOR _104_ (
    .A(_006_),
    .B(_024_),
    .Y(_036_)
  );
  NOR _105_ (
    .A(_028_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _106_ (
    .A(_035_),
    .B(_037_),
    .Y(_000_[4])
  );
  NOR _107_ (
    .A(_007_),
    .B(_028_),
    .Y(_038_)
  );
  NOR _108_ (
    .A(_030_),
    .B(_038_),
    .Y(_039_)
  );
  NOR _109_ (
    .A(_035_),
    .B(_039_),
    .Y(_000_[5])
  );
  NOR _110_ (
    .A(_008_),
    .B(_030_),
    .Y(_040_)
  );
  NOR _111_ (
    .A(_032_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _112_ (
    .A(_035_),
    .B(_041_),
    .Y(_000_[6])
  );
  NOR _113_ (
    .A(_032_),
    .B(_034_),
    .Y(_000_[7])
  );
  NAND _114_ (
    .A(contador[2]),
    .B(contador[1]),
    .Y(_042_)
  );
  NOR _115_ (
    .A(contador[0]),
    .B(_042_),
    .Y(_043_)
  );
  NOR _116_ (
    .A(contador[3]),
    .B(valid_in),
    .Y(_044_)
  );
  NAND _117_ (
    .A(_019_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _118_ (
    .A(_043_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _119_ (
    .A(contador[2]),
    .B(_013_),
    .Y(_047_)
  );
  NAND _120_ (
    .A(contador[2]),
    .B(data_in[6]),
    .Y(_048_)
  );
  NAND _121_ (
    .A(contador[1]),
    .B(_048_),
    .Y(_049_)
  );
  NOR _122_ (
    .A(_047_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _123_ (
    .A(contador[2]),
    .B(_012_),
    .Y(_051_)
  );
  NOR _124_ (
    .A(data_in[4]),
    .B(_051_),
    .Y(_052_)
  );
  NOR _125_ (
    .A(data_in[0]),
    .B(_019_),
    .Y(_053_)
  );
  NOR _126_ (
    .A(_050_),
    .B(_053_),
    .Y(_054_)
  );
  NOT _127_ (
    .A(_054_),
    .Y(_055_)
  );
  NOR _128_ (
    .A(_052_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _129_ (
    .A(contador[0]),
    .B(_056_),
    .Y(_057_)
  );
  NAND _130_ (
    .A(_004_),
    .B(data_in[3]),
    .Y(_058_)
  );
  NOR _131_ (
    .A(_004_),
    .B(_014_),
    .Y(_059_)
  );
  NOR _132_ (
    .A(_012_),
    .B(_059_),
    .Y(_060_)
  );
  NAND _133_ (
    .A(_058_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _134_ (
    .A(data_in[5]),
    .B(_051_),
    .Y(_062_)
  );
  NOR _135_ (
    .A(data_in[1]),
    .B(_019_),
    .Y(_063_)
  );
  NOR _136_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _137_ (
    .A(_061_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _138_ (
    .A(contador[0]),
    .B(_065_),
    .Y(_066_)
  );
  NOR _139_ (
    .A(contador[3]),
    .B(_011_),
    .Y(_067_)
  );
  NAND _140_ (
    .A(_066_),
    .B(_067_),
    .Y(_001_)
  );
  NOR _141_ (
    .A(_057_),
    .B(_001_),
    .Y(_002_)
  );
  NOR _142_ (
    .A(_046_),
    .B(_002_),
    .Y(_003_)
  );
  NOR _143_ (
    .A(_010_),
    .B(_003_),
    .Y(data_out)
  );
  (* src = "Paralelo_SerialSynth.v:25" *)
  DFF _144_ (
    .C(clk_32f),
    .D(_000_[0]),
    .Q(contador[0])
  );
  (* src = "Paralelo_SerialSynth.v:25" *)
  DFF _145_ (
    .C(clk_32f),
    .D(_000_[1]),
    .Q(contador[1])
  );
  (* src = "Paralelo_SerialSynth.v:25" *)
  DFF _146_ (
    .C(clk_32f),
    .D(_000_[2]),
    .Q(contador[2])
  );
  (* src = "Paralelo_SerialSynth.v:25" *)
  DFF _147_ (
    .C(clk_32f),
    .D(_000_[3]),
    .Q(contador[3])
  );
  (* src = "Paralelo_SerialSynth.v:25" *)
  DFF _148_ (
    .C(clk_32f),
    .D(_000_[4]),
    .Q(contador[4])
  );
  (* src = "Paralelo_SerialSynth.v:25" *)
  DFF _149_ (
    .C(clk_32f),
    .D(_000_[5]),
    .Q(contador[5])
  );
  (* src = "Paralelo_SerialSynth.v:25" *)
  DFF _150_ (
    .C(clk_32f),
    .D(_000_[6]),
    .Q(contador[6])
  );
  (* src = "Paralelo_SerialSynth.v:25" *)
  DFF _151_ (
    .C(clk_32f),
    .D(_000_[7]),
    .Q(contador[7])
  );
endmodule

(* src = "bytestripingSynth.v:1" *)
module bytestripingSynth(data_in, clk_2f, clk_f, valid_in, reset, lane_0, lane_1, valid_out0, valid_out1);
  (* src = "bytestripingSynth.v:9" *)
  wire [31:0] _000_;
  (* src = "bytestripingSynth.v:9" *)
  wire [31:0] _001_;
  (* src = "bytestripingSynth.v:9" *)
  wire _002_;
  (* src = "bytestripingSynth.v:9" *)
  wire _003_;
  (* src = "bytestripingSynth.v:9" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  (* src = "bytestripingSynth.v:3" *)
  input clk_2f;
  (* src = "bytestripingSynth.v:3" *)
  input clk_f;
  (* src = "bytestripingSynth.v:2" *)
  input [31:0] data_in;
  (* src = "bytestripingSynth.v:4" *)
  output [31:0] lane_0;
  (* src = "bytestripingSynth.v:4" *)
  output [31:0] lane_1;
  (* src = "bytestripingSynth.v:3" *)
  input reset;
  (* src = "bytestripingSynth.v:7" *)
  wire selector;
  (* src = "bytestripingSynth.v:3" *)
  input valid_in;
  (* src = "bytestripingSynth.v:5" *)
  output valid_out0;
  (* src = "bytestripingSynth.v:5" *)
  output valid_out1;
  NOT _239_ (
    .A(selector),
    .Y(_005_)
  );
  NOT _240_ (
    .A(reset),
    .Y(_006_)
  );
  NOT _241_ (
    .A(data_in[0]),
    .Y(_007_)
  );
  NOT _242_ (
    .A(data_in[1]),
    .Y(_008_)
  );
  NOT _243_ (
    .A(data_in[2]),
    .Y(_009_)
  );
  NOT _244_ (
    .A(data_in[3]),
    .Y(_010_)
  );
  NOT _245_ (
    .A(data_in[4]),
    .Y(_011_)
  );
  NOT _246_ (
    .A(data_in[5]),
    .Y(_012_)
  );
  NOT _247_ (
    .A(data_in[6]),
    .Y(_013_)
  );
  NOT _248_ (
    .A(data_in[7]),
    .Y(_014_)
  );
  NOT _249_ (
    .A(data_in[8]),
    .Y(_015_)
  );
  NOT _250_ (
    .A(data_in[9]),
    .Y(_016_)
  );
  NOT _251_ (
    .A(data_in[10]),
    .Y(_017_)
  );
  NOT _252_ (
    .A(data_in[11]),
    .Y(_018_)
  );
  NOT _253_ (
    .A(data_in[12]),
    .Y(_019_)
  );
  NOT _254_ (
    .A(data_in[13]),
    .Y(_020_)
  );
  NOT _255_ (
    .A(data_in[14]),
    .Y(_021_)
  );
  NOT _256_ (
    .A(data_in[15]),
    .Y(_022_)
  );
  NOT _257_ (
    .A(data_in[16]),
    .Y(_023_)
  );
  NOT _258_ (
    .A(data_in[17]),
    .Y(_024_)
  );
  NOT _259_ (
    .A(data_in[18]),
    .Y(_025_)
  );
  NOT _260_ (
    .A(data_in[19]),
    .Y(_026_)
  );
  NOT _261_ (
    .A(data_in[20]),
    .Y(_027_)
  );
  NOT _262_ (
    .A(data_in[21]),
    .Y(_028_)
  );
  NOT _263_ (
    .A(data_in[22]),
    .Y(_029_)
  );
  NOT _264_ (
    .A(data_in[23]),
    .Y(_030_)
  );
  NOT _265_ (
    .A(data_in[24]),
    .Y(_031_)
  );
  NOT _266_ (
    .A(data_in[25]),
    .Y(_032_)
  );
  NOT _267_ (
    .A(data_in[26]),
    .Y(_033_)
  );
  NOT _268_ (
    .A(data_in[27]),
    .Y(_034_)
  );
  NOT _269_ (
    .A(data_in[28]),
    .Y(_035_)
  );
  NOT _270_ (
    .A(data_in[29]),
    .Y(_036_)
  );
  NOT _271_ (
    .A(data_in[30]),
    .Y(_037_)
  );
  NOT _272_ (
    .A(data_in[31]),
    .Y(_038_)
  );
  NAND _273_ (
    .A(valid_in),
    .B(selector),
    .Y(_039_)
  );
  NOR _274_ (
    .A(_006_),
    .B(_039_),
    .Y(_040_)
  );
  NOT _275_ (
    .A(_040_),
    .Y(_041_)
  );
  NAND _276_ (
    .A(data_in[0]),
    .B(_040_),
    .Y(_042_)
  );
  NOR _277_ (
    .A(selector),
    .B(_006_),
    .Y(_002_)
  );
  NAND _278_ (
    .A(lane_1[0]),
    .B(_002_),
    .Y(_043_)
  );
  NAND _279_ (
    .A(_042_),
    .B(_043_),
    .Y(_001_[0])
  );
  NAND _280_ (
    .A(lane_1[1]),
    .B(_002_),
    .Y(_044_)
  );
  NAND _281_ (
    .A(data_in[1]),
    .B(_040_),
    .Y(_045_)
  );
  NAND _282_ (
    .A(_044_),
    .B(_045_),
    .Y(_001_[1])
  );
  NAND _283_ (
    .A(lane_1[2]),
    .B(_002_),
    .Y(_046_)
  );
  NAND _284_ (
    .A(data_in[2]),
    .B(_040_),
    .Y(_047_)
  );
  NAND _285_ (
    .A(_046_),
    .B(_047_),
    .Y(_001_[2])
  );
  NAND _286_ (
    .A(lane_1[3]),
    .B(_002_),
    .Y(_048_)
  );
  NAND _287_ (
    .A(data_in[3]),
    .B(_040_),
    .Y(_049_)
  );
  NAND _288_ (
    .A(_048_),
    .B(_049_),
    .Y(_001_[3])
  );
  NAND _289_ (
    .A(lane_1[4]),
    .B(_002_),
    .Y(_050_)
  );
  NAND _290_ (
    .A(data_in[4]),
    .B(_040_),
    .Y(_051_)
  );
  NAND _291_ (
    .A(_050_),
    .B(_051_),
    .Y(_001_[4])
  );
  NAND _292_ (
    .A(lane_1[5]),
    .B(_002_),
    .Y(_052_)
  );
  NAND _293_ (
    .A(data_in[5]),
    .B(_040_),
    .Y(_053_)
  );
  NAND _294_ (
    .A(_052_),
    .B(_053_),
    .Y(_001_[5])
  );
  NAND _295_ (
    .A(lane_1[6]),
    .B(_002_),
    .Y(_054_)
  );
  NAND _296_ (
    .A(data_in[6]),
    .B(_040_),
    .Y(_055_)
  );
  NAND _297_ (
    .A(_054_),
    .B(_055_),
    .Y(_001_[6])
  );
  NAND _298_ (
    .A(lane_1[7]),
    .B(_002_),
    .Y(_056_)
  );
  NAND _299_ (
    .A(data_in[7]),
    .B(_040_),
    .Y(_057_)
  );
  NAND _300_ (
    .A(_056_),
    .B(_057_),
    .Y(_001_[7])
  );
  NAND _301_ (
    .A(lane_1[8]),
    .B(_002_),
    .Y(_058_)
  );
  NAND _302_ (
    .A(data_in[8]),
    .B(_040_),
    .Y(_059_)
  );
  NAND _303_ (
    .A(_058_),
    .B(_059_),
    .Y(_001_[8])
  );
  NAND _304_ (
    .A(lane_1[9]),
    .B(_002_),
    .Y(_060_)
  );
  NAND _305_ (
    .A(data_in[9]),
    .B(_040_),
    .Y(_061_)
  );
  NAND _306_ (
    .A(_060_),
    .B(_061_),
    .Y(_001_[9])
  );
  NAND _307_ (
    .A(lane_1[10]),
    .B(_002_),
    .Y(_062_)
  );
  NAND _308_ (
    .A(data_in[10]),
    .B(_040_),
    .Y(_063_)
  );
  NAND _309_ (
    .A(_062_),
    .B(_063_),
    .Y(_001_[10])
  );
  NAND _310_ (
    .A(lane_1[11]),
    .B(_002_),
    .Y(_064_)
  );
  NAND _311_ (
    .A(data_in[11]),
    .B(_040_),
    .Y(_065_)
  );
  NAND _312_ (
    .A(_064_),
    .B(_065_),
    .Y(_001_[11])
  );
  NAND _313_ (
    .A(lane_1[12]),
    .B(_002_),
    .Y(_066_)
  );
  NAND _314_ (
    .A(data_in[12]),
    .B(_040_),
    .Y(_067_)
  );
  NAND _315_ (
    .A(_066_),
    .B(_067_),
    .Y(_001_[12])
  );
  NAND _316_ (
    .A(lane_1[13]),
    .B(_002_),
    .Y(_068_)
  );
  NAND _317_ (
    .A(data_in[13]),
    .B(_040_),
    .Y(_069_)
  );
  NAND _318_ (
    .A(_068_),
    .B(_069_),
    .Y(_001_[13])
  );
  NAND _319_ (
    .A(lane_1[14]),
    .B(_002_),
    .Y(_070_)
  );
  NAND _320_ (
    .A(data_in[14]),
    .B(_040_),
    .Y(_071_)
  );
  NAND _321_ (
    .A(_070_),
    .B(_071_),
    .Y(_001_[14])
  );
  NAND _322_ (
    .A(lane_1[15]),
    .B(_002_),
    .Y(_072_)
  );
  NAND _323_ (
    .A(data_in[15]),
    .B(_040_),
    .Y(_073_)
  );
  NAND _324_ (
    .A(_072_),
    .B(_073_),
    .Y(_001_[15])
  );
  NAND _325_ (
    .A(lane_1[16]),
    .B(_002_),
    .Y(_074_)
  );
  NAND _326_ (
    .A(data_in[16]),
    .B(_040_),
    .Y(_075_)
  );
  NAND _327_ (
    .A(_074_),
    .B(_075_),
    .Y(_001_[16])
  );
  NAND _328_ (
    .A(lane_1[17]),
    .B(_002_),
    .Y(_076_)
  );
  NAND _329_ (
    .A(data_in[17]),
    .B(_040_),
    .Y(_077_)
  );
  NAND _330_ (
    .A(_076_),
    .B(_077_),
    .Y(_001_[17])
  );
  NAND _331_ (
    .A(lane_1[18]),
    .B(_002_),
    .Y(_078_)
  );
  NAND _332_ (
    .A(data_in[18]),
    .B(_040_),
    .Y(_079_)
  );
  NAND _333_ (
    .A(_078_),
    .B(_079_),
    .Y(_001_[18])
  );
  NAND _334_ (
    .A(lane_1[19]),
    .B(_002_),
    .Y(_080_)
  );
  NAND _335_ (
    .A(data_in[19]),
    .B(_040_),
    .Y(_081_)
  );
  NAND _336_ (
    .A(_080_),
    .B(_081_),
    .Y(_001_[19])
  );
  NAND _337_ (
    .A(lane_1[20]),
    .B(_002_),
    .Y(_082_)
  );
  NAND _338_ (
    .A(data_in[20]),
    .B(_040_),
    .Y(_083_)
  );
  NAND _339_ (
    .A(_082_),
    .B(_083_),
    .Y(_001_[20])
  );
  NAND _340_ (
    .A(lane_1[21]),
    .B(_002_),
    .Y(_084_)
  );
  NAND _341_ (
    .A(data_in[21]),
    .B(_040_),
    .Y(_085_)
  );
  NAND _342_ (
    .A(_084_),
    .B(_085_),
    .Y(_001_[21])
  );
  NAND _343_ (
    .A(lane_1[22]),
    .B(_002_),
    .Y(_086_)
  );
  NAND _344_ (
    .A(data_in[22]),
    .B(_040_),
    .Y(_087_)
  );
  NAND _345_ (
    .A(_086_),
    .B(_087_),
    .Y(_001_[22])
  );
  NAND _346_ (
    .A(lane_1[23]),
    .B(_002_),
    .Y(_088_)
  );
  NAND _347_ (
    .A(data_in[23]),
    .B(_040_),
    .Y(_089_)
  );
  NAND _348_ (
    .A(_088_),
    .B(_089_),
    .Y(_001_[23])
  );
  NAND _349_ (
    .A(lane_1[24]),
    .B(_002_),
    .Y(_090_)
  );
  NAND _350_ (
    .A(data_in[24]),
    .B(_040_),
    .Y(_091_)
  );
  NAND _351_ (
    .A(_090_),
    .B(_091_),
    .Y(_001_[24])
  );
  NAND _352_ (
    .A(lane_1[25]),
    .B(_002_),
    .Y(_092_)
  );
  NAND _353_ (
    .A(data_in[25]),
    .B(_040_),
    .Y(_093_)
  );
  NAND _354_ (
    .A(_092_),
    .B(_093_),
    .Y(_001_[25])
  );
  NAND _355_ (
    .A(lane_1[26]),
    .B(_002_),
    .Y(_094_)
  );
  NAND _356_ (
    .A(data_in[26]),
    .B(_040_),
    .Y(_095_)
  );
  NAND _357_ (
    .A(_094_),
    .B(_095_),
    .Y(_001_[26])
  );
  NAND _358_ (
    .A(lane_1[27]),
    .B(_002_),
    .Y(_096_)
  );
  NAND _359_ (
    .A(data_in[27]),
    .B(_040_),
    .Y(_097_)
  );
  NAND _360_ (
    .A(_096_),
    .B(_097_),
    .Y(_001_[27])
  );
  NAND _361_ (
    .A(lane_1[28]),
    .B(_002_),
    .Y(_098_)
  );
  NAND _362_ (
    .A(data_in[28]),
    .B(_040_),
    .Y(_099_)
  );
  NAND _363_ (
    .A(_098_),
    .B(_099_),
    .Y(_001_[28])
  );
  NAND _364_ (
    .A(lane_1[29]),
    .B(_002_),
    .Y(_100_)
  );
  NAND _365_ (
    .A(data_in[29]),
    .B(_040_),
    .Y(_101_)
  );
  NAND _366_ (
    .A(_100_),
    .B(_101_),
    .Y(_001_[29])
  );
  NAND _367_ (
    .A(lane_1[30]),
    .B(_002_),
    .Y(_102_)
  );
  NAND _368_ (
    .A(data_in[30]),
    .B(_040_),
    .Y(_103_)
  );
  NAND _369_ (
    .A(_102_),
    .B(_103_),
    .Y(_001_[30])
  );
  NAND _370_ (
    .A(lane_1[31]),
    .B(_002_),
    .Y(_104_)
  );
  NAND _371_ (
    .A(data_in[31]),
    .B(_040_),
    .Y(_105_)
  );
  NAND _372_ (
    .A(_104_),
    .B(_105_),
    .Y(_001_[31])
  );
  NAND _373_ (
    .A(valid_out1),
    .B(_002_),
    .Y(_106_)
  );
  NAND _374_ (
    .A(_041_),
    .B(_106_),
    .Y(_004_)
  );
  NAND _375_ (
    .A(selector),
    .B(valid_out0),
    .Y(_107_)
  );
  NAND _376_ (
    .A(valid_in),
    .B(_005_),
    .Y(_108_)
  );
  NAND _377_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  NAND _378_ (
    .A(reset),
    .B(_109_),
    .Y(_110_)
  );
  NOT _379_ (
    .A(_110_),
    .Y(_003_)
  );
  NAND _380_ (
    .A(selector),
    .B(lane_0[0]),
    .Y(_111_)
  );
  NOT _381_ (
    .A(_111_),
    .Y(_112_)
  );
  NOR _382_ (
    .A(_007_),
    .B(_108_),
    .Y(_113_)
  );
  NOR _383_ (
    .A(_112_),
    .B(_113_),
    .Y(_114_)
  );
  NOR _384_ (
    .A(_006_),
    .B(_114_),
    .Y(_000_[0])
  );
  NAND _385_ (
    .A(selector),
    .B(lane_0[1]),
    .Y(_115_)
  );
  NOT _386_ (
    .A(_115_),
    .Y(_116_)
  );
  NOR _387_ (
    .A(_008_),
    .B(_108_),
    .Y(_117_)
  );
  NOR _388_ (
    .A(_116_),
    .B(_117_),
    .Y(_118_)
  );
  NOR _389_ (
    .A(_006_),
    .B(_118_),
    .Y(_000_[1])
  );
  NAND _390_ (
    .A(selector),
    .B(lane_0[2]),
    .Y(_119_)
  );
  NOT _391_ (
    .A(_119_),
    .Y(_120_)
  );
  NOR _392_ (
    .A(_009_),
    .B(_108_),
    .Y(_121_)
  );
  NOR _393_ (
    .A(_120_),
    .B(_121_),
    .Y(_122_)
  );
  NOR _394_ (
    .A(_006_),
    .B(_122_),
    .Y(_000_[2])
  );
  NAND _395_ (
    .A(selector),
    .B(lane_0[3]),
    .Y(_123_)
  );
  NOT _396_ (
    .A(_123_),
    .Y(_124_)
  );
  NOR _397_ (
    .A(_010_),
    .B(_108_),
    .Y(_125_)
  );
  NOR _398_ (
    .A(_124_),
    .B(_125_),
    .Y(_126_)
  );
  NOR _399_ (
    .A(_006_),
    .B(_126_),
    .Y(_000_[3])
  );
  NAND _400_ (
    .A(selector),
    .B(lane_0[4]),
    .Y(_127_)
  );
  NOT _401_ (
    .A(_127_),
    .Y(_128_)
  );
  NOR _402_ (
    .A(_011_),
    .B(_108_),
    .Y(_129_)
  );
  NOR _403_ (
    .A(_128_),
    .B(_129_),
    .Y(_130_)
  );
  NOR _404_ (
    .A(_006_),
    .B(_130_),
    .Y(_000_[4])
  );
  NAND _405_ (
    .A(selector),
    .B(lane_0[5]),
    .Y(_131_)
  );
  NOT _406_ (
    .A(_131_),
    .Y(_132_)
  );
  NOR _407_ (
    .A(_012_),
    .B(_108_),
    .Y(_133_)
  );
  NOR _408_ (
    .A(_132_),
    .B(_133_),
    .Y(_134_)
  );
  NOR _409_ (
    .A(_006_),
    .B(_134_),
    .Y(_000_[5])
  );
  NAND _410_ (
    .A(selector),
    .B(lane_0[6]),
    .Y(_135_)
  );
  NOT _411_ (
    .A(_135_),
    .Y(_136_)
  );
  NOR _412_ (
    .A(_013_),
    .B(_108_),
    .Y(_137_)
  );
  NOR _413_ (
    .A(_136_),
    .B(_137_),
    .Y(_138_)
  );
  NOR _414_ (
    .A(_006_),
    .B(_138_),
    .Y(_000_[6])
  );
  NAND _415_ (
    .A(selector),
    .B(lane_0[7]),
    .Y(_139_)
  );
  NOT _416_ (
    .A(_139_),
    .Y(_140_)
  );
  NOR _417_ (
    .A(_014_),
    .B(_108_),
    .Y(_141_)
  );
  NOR _418_ (
    .A(_140_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _419_ (
    .A(_006_),
    .B(_142_),
    .Y(_000_[7])
  );
  NAND _420_ (
    .A(selector),
    .B(lane_0[8]),
    .Y(_143_)
  );
  NOT _421_ (
    .A(_143_),
    .Y(_144_)
  );
  NOR _422_ (
    .A(_015_),
    .B(_108_),
    .Y(_145_)
  );
  NOR _423_ (
    .A(_144_),
    .B(_145_),
    .Y(_146_)
  );
  NOR _424_ (
    .A(_006_),
    .B(_146_),
    .Y(_000_[8])
  );
  NAND _425_ (
    .A(selector),
    .B(lane_0[9]),
    .Y(_147_)
  );
  NOT _426_ (
    .A(_147_),
    .Y(_148_)
  );
  NOR _427_ (
    .A(_016_),
    .B(_108_),
    .Y(_149_)
  );
  NOR _428_ (
    .A(_148_),
    .B(_149_),
    .Y(_150_)
  );
  NOR _429_ (
    .A(_006_),
    .B(_150_),
    .Y(_000_[9])
  );
  NAND _430_ (
    .A(selector),
    .B(lane_0[10]),
    .Y(_151_)
  );
  NOT _431_ (
    .A(_151_),
    .Y(_152_)
  );
  NOR _432_ (
    .A(_017_),
    .B(_108_),
    .Y(_153_)
  );
  NOR _433_ (
    .A(_152_),
    .B(_153_),
    .Y(_154_)
  );
  NOR _434_ (
    .A(_006_),
    .B(_154_),
    .Y(_000_[10])
  );
  NAND _435_ (
    .A(selector),
    .B(lane_0[11]),
    .Y(_155_)
  );
  NOT _436_ (
    .A(_155_),
    .Y(_156_)
  );
  NOR _437_ (
    .A(_018_),
    .B(_108_),
    .Y(_157_)
  );
  NOR _438_ (
    .A(_156_),
    .B(_157_),
    .Y(_158_)
  );
  NOR _439_ (
    .A(_006_),
    .B(_158_),
    .Y(_000_[11])
  );
  NAND _440_ (
    .A(selector),
    .B(lane_0[12]),
    .Y(_159_)
  );
  NOT _441_ (
    .A(_159_),
    .Y(_160_)
  );
  NOR _442_ (
    .A(_019_),
    .B(_108_),
    .Y(_161_)
  );
  NOR _443_ (
    .A(_160_),
    .B(_161_),
    .Y(_162_)
  );
  NOR _444_ (
    .A(_006_),
    .B(_162_),
    .Y(_000_[12])
  );
  NAND _445_ (
    .A(selector),
    .B(lane_0[13]),
    .Y(_163_)
  );
  NOT _446_ (
    .A(_163_),
    .Y(_164_)
  );
  NOR _447_ (
    .A(_020_),
    .B(_108_),
    .Y(_165_)
  );
  NOR _448_ (
    .A(_164_),
    .B(_165_),
    .Y(_166_)
  );
  NOR _449_ (
    .A(_006_),
    .B(_166_),
    .Y(_000_[13])
  );
  NAND _450_ (
    .A(selector),
    .B(lane_0[14]),
    .Y(_167_)
  );
  NOT _451_ (
    .A(_167_),
    .Y(_168_)
  );
  NOR _452_ (
    .A(_021_),
    .B(_108_),
    .Y(_169_)
  );
  NOR _453_ (
    .A(_168_),
    .B(_169_),
    .Y(_170_)
  );
  NOR _454_ (
    .A(_006_),
    .B(_170_),
    .Y(_000_[14])
  );
  NAND _455_ (
    .A(selector),
    .B(lane_0[15]),
    .Y(_171_)
  );
  NOT _456_ (
    .A(_171_),
    .Y(_172_)
  );
  NOR _457_ (
    .A(_022_),
    .B(_108_),
    .Y(_173_)
  );
  NOR _458_ (
    .A(_172_),
    .B(_173_),
    .Y(_174_)
  );
  NOR _459_ (
    .A(_006_),
    .B(_174_),
    .Y(_000_[15])
  );
  NAND _460_ (
    .A(selector),
    .B(lane_0[16]),
    .Y(_175_)
  );
  NOT _461_ (
    .A(_175_),
    .Y(_176_)
  );
  NOR _462_ (
    .A(_023_),
    .B(_108_),
    .Y(_177_)
  );
  NOR _463_ (
    .A(_176_),
    .B(_177_),
    .Y(_178_)
  );
  NOR _464_ (
    .A(_006_),
    .B(_178_),
    .Y(_000_[16])
  );
  NAND _465_ (
    .A(selector),
    .B(lane_0[17]),
    .Y(_179_)
  );
  NOT _466_ (
    .A(_179_),
    .Y(_180_)
  );
  NOR _467_ (
    .A(_024_),
    .B(_108_),
    .Y(_181_)
  );
  NOR _468_ (
    .A(_180_),
    .B(_181_),
    .Y(_182_)
  );
  NOR _469_ (
    .A(_006_),
    .B(_182_),
    .Y(_000_[17])
  );
  NAND _470_ (
    .A(selector),
    .B(lane_0[18]),
    .Y(_183_)
  );
  NOT _471_ (
    .A(_183_),
    .Y(_184_)
  );
  NOR _472_ (
    .A(_025_),
    .B(_108_),
    .Y(_185_)
  );
  NOR _473_ (
    .A(_184_),
    .B(_185_),
    .Y(_186_)
  );
  NOR _474_ (
    .A(_006_),
    .B(_186_),
    .Y(_000_[18])
  );
  NAND _475_ (
    .A(selector),
    .B(lane_0[19]),
    .Y(_187_)
  );
  NOT _476_ (
    .A(_187_),
    .Y(_188_)
  );
  NOR _477_ (
    .A(_026_),
    .B(_108_),
    .Y(_189_)
  );
  NOR _478_ (
    .A(_188_),
    .B(_189_),
    .Y(_190_)
  );
  NOR _479_ (
    .A(_006_),
    .B(_190_),
    .Y(_000_[19])
  );
  NAND _480_ (
    .A(selector),
    .B(lane_0[20]),
    .Y(_191_)
  );
  NOT _481_ (
    .A(_191_),
    .Y(_192_)
  );
  NOR _482_ (
    .A(_027_),
    .B(_108_),
    .Y(_193_)
  );
  NOR _483_ (
    .A(_192_),
    .B(_193_),
    .Y(_194_)
  );
  NOR _484_ (
    .A(_006_),
    .B(_194_),
    .Y(_000_[20])
  );
  NAND _485_ (
    .A(selector),
    .B(lane_0[21]),
    .Y(_195_)
  );
  NOT _486_ (
    .A(_195_),
    .Y(_196_)
  );
  NOR _487_ (
    .A(_028_),
    .B(_108_),
    .Y(_197_)
  );
  NOR _488_ (
    .A(_196_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _489_ (
    .A(_006_),
    .B(_198_),
    .Y(_000_[21])
  );
  NAND _490_ (
    .A(selector),
    .B(lane_0[22]),
    .Y(_199_)
  );
  NOT _491_ (
    .A(_199_),
    .Y(_200_)
  );
  NOR _492_ (
    .A(_029_),
    .B(_108_),
    .Y(_201_)
  );
  NOR _493_ (
    .A(_200_),
    .B(_201_),
    .Y(_202_)
  );
  NOR _494_ (
    .A(_006_),
    .B(_202_),
    .Y(_000_[22])
  );
  NAND _495_ (
    .A(selector),
    .B(lane_0[23]),
    .Y(_203_)
  );
  NOT _496_ (
    .A(_203_),
    .Y(_204_)
  );
  NOR _497_ (
    .A(_030_),
    .B(_108_),
    .Y(_205_)
  );
  NOR _498_ (
    .A(_204_),
    .B(_205_),
    .Y(_206_)
  );
  NOR _499_ (
    .A(_006_),
    .B(_206_),
    .Y(_000_[23])
  );
  NAND _500_ (
    .A(selector),
    .B(lane_0[24]),
    .Y(_207_)
  );
  NOT _501_ (
    .A(_207_),
    .Y(_208_)
  );
  NOR _502_ (
    .A(_031_),
    .B(_108_),
    .Y(_209_)
  );
  NOR _503_ (
    .A(_208_),
    .B(_209_),
    .Y(_210_)
  );
  NOR _504_ (
    .A(_006_),
    .B(_210_),
    .Y(_000_[24])
  );
  NAND _505_ (
    .A(selector),
    .B(lane_0[25]),
    .Y(_211_)
  );
  NOT _506_ (
    .A(_211_),
    .Y(_212_)
  );
  NOR _507_ (
    .A(_032_),
    .B(_108_),
    .Y(_213_)
  );
  NOR _508_ (
    .A(_212_),
    .B(_213_),
    .Y(_214_)
  );
  NOR _509_ (
    .A(_006_),
    .B(_214_),
    .Y(_000_[25])
  );
  NAND _510_ (
    .A(selector),
    .B(lane_0[26]),
    .Y(_215_)
  );
  NOT _511_ (
    .A(_215_),
    .Y(_216_)
  );
  NOR _512_ (
    .A(_033_),
    .B(_108_),
    .Y(_217_)
  );
  NOR _513_ (
    .A(_216_),
    .B(_217_),
    .Y(_218_)
  );
  NOR _514_ (
    .A(_006_),
    .B(_218_),
    .Y(_000_[26])
  );
  NAND _515_ (
    .A(selector),
    .B(lane_0[27]),
    .Y(_219_)
  );
  NOT _516_ (
    .A(_219_),
    .Y(_220_)
  );
  NOR _517_ (
    .A(_034_),
    .B(_108_),
    .Y(_221_)
  );
  NOR _518_ (
    .A(_220_),
    .B(_221_),
    .Y(_222_)
  );
  NOR _519_ (
    .A(_006_),
    .B(_222_),
    .Y(_000_[27])
  );
  NAND _520_ (
    .A(selector),
    .B(lane_0[28]),
    .Y(_223_)
  );
  NOT _521_ (
    .A(_223_),
    .Y(_224_)
  );
  NOR _522_ (
    .A(_035_),
    .B(_108_),
    .Y(_225_)
  );
  NOR _523_ (
    .A(_224_),
    .B(_225_),
    .Y(_226_)
  );
  NOR _524_ (
    .A(_006_),
    .B(_226_),
    .Y(_000_[28])
  );
  NAND _525_ (
    .A(selector),
    .B(lane_0[29]),
    .Y(_227_)
  );
  NOT _526_ (
    .A(_227_),
    .Y(_228_)
  );
  NOR _527_ (
    .A(_036_),
    .B(_108_),
    .Y(_229_)
  );
  NOR _528_ (
    .A(_228_),
    .B(_229_),
    .Y(_230_)
  );
  NOR _529_ (
    .A(_006_),
    .B(_230_),
    .Y(_000_[29])
  );
  NAND _530_ (
    .A(selector),
    .B(lane_0[30]),
    .Y(_231_)
  );
  NOT _531_ (
    .A(_231_),
    .Y(_232_)
  );
  NOR _532_ (
    .A(_037_),
    .B(_108_),
    .Y(_233_)
  );
  NOR _533_ (
    .A(_232_),
    .B(_233_),
    .Y(_234_)
  );
  NOR _534_ (
    .A(_006_),
    .B(_234_),
    .Y(_000_[30])
  );
  NAND _535_ (
    .A(selector),
    .B(lane_0[31]),
    .Y(_235_)
  );
  NOT _536_ (
    .A(_235_),
    .Y(_236_)
  );
  NOR _537_ (
    .A(_038_),
    .B(_108_),
    .Y(_237_)
  );
  NOR _538_ (
    .A(_236_),
    .B(_237_),
    .Y(_238_)
  );
  NOR _539_ (
    .A(_006_),
    .B(_238_),
    .Y(_000_[31])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _540_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(lane_0[0])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _541_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(lane_0[1])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _542_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(lane_0[2])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _543_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(lane_0[3])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _544_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(lane_0[4])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _545_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(lane_0[5])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _546_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(lane_0[6])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _547_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(lane_0[7])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _548_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(lane_0[8])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _549_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(lane_0[9])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _550_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(lane_0[10])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _551_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(lane_0[11])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _552_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(lane_0[12])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _553_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(lane_0[13])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _554_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(lane_0[14])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _555_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(lane_0[15])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _556_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(lane_0[16])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _557_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(lane_0[17])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _558_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(lane_0[18])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _559_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(lane_0[19])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _560_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(lane_0[20])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _561_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(lane_0[21])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _562_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(lane_0[22])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _563_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(lane_0[23])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _564_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(lane_0[24])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _565_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(lane_0[25])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _566_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(lane_0[26])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _567_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(lane_0[27])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _568_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(lane_0[28])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _569_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(lane_0[29])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _570_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(lane_0[30])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _571_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(lane_0[31])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _572_ (
    .C(clk_2f),
    .D(_003_),
    .Q(valid_out0)
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _573_ (
    .C(clk_2f),
    .D(_004_),
    .Q(valid_out1)
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _574_ (
    .C(clk_2f),
    .D(_002_),
    .Q(selector)
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _575_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(lane_1[0])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _576_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(lane_1[1])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _577_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(lane_1[2])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _578_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(lane_1[3])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _579_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(lane_1[4])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _580_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(lane_1[5])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _581_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(lane_1[6])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _582_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(lane_1[7])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _583_ (
    .C(clk_2f),
    .D(_001_[8]),
    .Q(lane_1[8])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _584_ (
    .C(clk_2f),
    .D(_001_[9]),
    .Q(lane_1[9])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _585_ (
    .C(clk_2f),
    .D(_001_[10]),
    .Q(lane_1[10])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _586_ (
    .C(clk_2f),
    .D(_001_[11]),
    .Q(lane_1[11])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _587_ (
    .C(clk_2f),
    .D(_001_[12]),
    .Q(lane_1[12])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _588_ (
    .C(clk_2f),
    .D(_001_[13]),
    .Q(lane_1[13])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _589_ (
    .C(clk_2f),
    .D(_001_[14]),
    .Q(lane_1[14])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _590_ (
    .C(clk_2f),
    .D(_001_[15]),
    .Q(lane_1[15])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _591_ (
    .C(clk_2f),
    .D(_001_[16]),
    .Q(lane_1[16])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _592_ (
    .C(clk_2f),
    .D(_001_[17]),
    .Q(lane_1[17])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _593_ (
    .C(clk_2f),
    .D(_001_[18]),
    .Q(lane_1[18])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _594_ (
    .C(clk_2f),
    .D(_001_[19]),
    .Q(lane_1[19])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _595_ (
    .C(clk_2f),
    .D(_001_[20]),
    .Q(lane_1[20])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _596_ (
    .C(clk_2f),
    .D(_001_[21]),
    .Q(lane_1[21])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _597_ (
    .C(clk_2f),
    .D(_001_[22]),
    .Q(lane_1[22])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _598_ (
    .C(clk_2f),
    .D(_001_[23]),
    .Q(lane_1[23])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _599_ (
    .C(clk_2f),
    .D(_001_[24]),
    .Q(lane_1[24])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _600_ (
    .C(clk_2f),
    .D(_001_[25]),
    .Q(lane_1[25])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _601_ (
    .C(clk_2f),
    .D(_001_[26]),
    .Q(lane_1[26])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _602_ (
    .C(clk_2f),
    .D(_001_[27]),
    .Q(lane_1[27])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _603_ (
    .C(clk_2f),
    .D(_001_[28]),
    .Q(lane_1[28])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _604_ (
    .C(clk_2f),
    .D(_001_[29]),
    .Q(lane_1[29])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _605_ (
    .C(clk_2f),
    .D(_001_[30]),
    .Q(lane_1[30])
  );
  (* src = "bytestripingSynth.v:9" *)
  DFF _606_ (
    .C(clk_2f),
    .D(_001_[31]),
    .Q(lane_1[31])
  );
endmodule

(* src = "log_32_8Synth.v:1" *)
module log_32_8Synth(clk_4f, data_in, valid, reset, data_out, valid_out);
  (* src = "log_32_8Synth.v:11" *)
  wire [7:0] _000_;
  (* src = "log_32_8Synth.v:11" *)
  wire [1:0] _001_;
  (* src = "log_32_8Synth.v:11" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  (* src = "log_32_8Synth.v:1" *)
  input clk_4f;
  (* src = "log_32_8Synth.v:2" *)
  input [31:0] data_in;
  (* src = "log_32_8Synth.v:5" *)
  output [7:0] data_out;
  (* src = "log_32_8Synth.v:4" *)
  input reset;
  (* src = "log_32_8Synth.v:8" *)
  wire [1:0] selector;
  (* src = "log_32_8Synth.v:3" *)
  input valid;
  (* src = "log_32_8Synth.v:6" *)
  output valid_out;
  NOT _068_ (
    .A(selector[0]),
    .Y(_031_)
  );
  NOT _069_ (
    .A(selector[1]),
    .Y(_032_)
  );
  NAND _070_ (
    .A(valid),
    .B(reset),
    .Y(_033_)
  );
  NOT _071_ (
    .A(_033_),
    .Y(_002_)
  );
  NOR _072_ (
    .A(selector[0]),
    .B(_033_),
    .Y(_001_[0])
  );
  NOR _073_ (
    .A(_031_),
    .B(_032_),
    .Y(_034_)
  );
  NOR _074_ (
    .A(selector[0]),
    .B(selector[1]),
    .Y(_035_)
  );
  NOR _075_ (
    .A(_033_),
    .B(_035_),
    .Y(_036_)
  );
  NOT _076_ (
    .A(_036_),
    .Y(_037_)
  );
  NOR _077_ (
    .A(_034_),
    .B(_037_),
    .Y(_001_[1])
  );
  NAND _078_ (
    .A(data_in[0]),
    .B(_034_),
    .Y(_038_)
  );
  NAND _079_ (
    .A(data_in[24]),
    .B(_035_),
    .Y(_039_)
  );
  NAND _080_ (
    .A(_038_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _081_ (
    .A(selector[0]),
    .B(_032_),
    .Y(_041_)
  );
  NAND _082_ (
    .A(data_in[8]),
    .B(_041_),
    .Y(_042_)
  );
  NOR _083_ (
    .A(_031_),
    .B(selector[1]),
    .Y(_043_)
  );
  NAND _084_ (
    .A(data_in[16]),
    .B(_043_),
    .Y(_044_)
  );
  NAND _085_ (
    .A(_042_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _086_ (
    .A(_040_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _087_ (
    .A(_033_),
    .B(_046_),
    .Y(_000_[0])
  );
  NAND _088_ (
    .A(data_in[1]),
    .B(_034_),
    .Y(_047_)
  );
  NAND _089_ (
    .A(data_in[9]),
    .B(_041_),
    .Y(_048_)
  );
  NAND _090_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _091_ (
    .A(data_in[25]),
    .B(_035_),
    .Y(_050_)
  );
  NAND _092_ (
    .A(data_in[17]),
    .B(_043_),
    .Y(_051_)
  );
  NAND _093_ (
    .A(_050_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _094_ (
    .A(_049_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _095_ (
    .A(_033_),
    .B(_053_),
    .Y(_000_[1])
  );
  NAND _096_ (
    .A(data_in[2]),
    .B(_034_),
    .Y(_054_)
  );
  NAND _097_ (
    .A(data_in[26]),
    .B(_035_),
    .Y(_055_)
  );
  NAND _098_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _099_ (
    .A(data_in[10]),
    .B(_041_),
    .Y(_057_)
  );
  NAND _100_ (
    .A(data_in[18]),
    .B(_043_),
    .Y(_058_)
  );
  NAND _101_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _102_ (
    .A(_056_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _103_ (
    .A(_033_),
    .B(_060_),
    .Y(_000_[2])
  );
  NAND _104_ (
    .A(data_in[3]),
    .B(_034_),
    .Y(_061_)
  );
  NAND _105_ (
    .A(data_in[11]),
    .B(_041_),
    .Y(_062_)
  );
  NAND _106_ (
    .A(_061_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _107_ (
    .A(data_in[27]),
    .B(_035_),
    .Y(_064_)
  );
  NAND _108_ (
    .A(data_in[19]),
    .B(_043_),
    .Y(_065_)
  );
  NAND _109_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _110_ (
    .A(_063_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _111_ (
    .A(_033_),
    .B(_067_),
    .Y(_000_[3])
  );
  NAND _112_ (
    .A(data_in[4]),
    .B(_034_),
    .Y(_003_)
  );
  NAND _113_ (
    .A(data_in[28]),
    .B(_035_),
    .Y(_004_)
  );
  NAND _114_ (
    .A(_003_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _115_ (
    .A(data_in[12]),
    .B(_041_),
    .Y(_006_)
  );
  NAND _116_ (
    .A(data_in[20]),
    .B(_043_),
    .Y(_007_)
  );
  NAND _117_ (
    .A(_006_),
    .B(_007_),
    .Y(_008_)
  );
  NOR _118_ (
    .A(_005_),
    .B(_008_),
    .Y(_009_)
  );
  NOR _119_ (
    .A(_033_),
    .B(_009_),
    .Y(_000_[4])
  );
  NAND _120_ (
    .A(data_in[5]),
    .B(_034_),
    .Y(_010_)
  );
  NAND _121_ (
    .A(data_in[29]),
    .B(_035_),
    .Y(_011_)
  );
  NAND _122_ (
    .A(_010_),
    .B(_011_),
    .Y(_012_)
  );
  NAND _123_ (
    .A(data_in[13]),
    .B(_041_),
    .Y(_013_)
  );
  NAND _124_ (
    .A(data_in[21]),
    .B(_043_),
    .Y(_014_)
  );
  NAND _125_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  NOR _126_ (
    .A(_012_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _127_ (
    .A(_033_),
    .B(_016_),
    .Y(_000_[5])
  );
  NAND _128_ (
    .A(data_in[6]),
    .B(_034_),
    .Y(_017_)
  );
  NAND _129_ (
    .A(data_in[30]),
    .B(_035_),
    .Y(_018_)
  );
  NAND _130_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _131_ (
    .A(data_in[14]),
    .B(_041_),
    .Y(_020_)
  );
  NAND _132_ (
    .A(data_in[22]),
    .B(_043_),
    .Y(_021_)
  );
  NAND _133_ (
    .A(_020_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _134_ (
    .A(_019_),
    .B(_022_),
    .Y(_023_)
  );
  NOR _135_ (
    .A(_033_),
    .B(_023_),
    .Y(_000_[6])
  );
  NAND _136_ (
    .A(data_in[7]),
    .B(_034_),
    .Y(_024_)
  );
  NAND _137_ (
    .A(data_in[31]),
    .B(_035_),
    .Y(_025_)
  );
  NAND _138_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  NAND _139_ (
    .A(data_in[15]),
    .B(_041_),
    .Y(_027_)
  );
  NAND _140_ (
    .A(data_in[23]),
    .B(_043_),
    .Y(_028_)
  );
  NAND _141_ (
    .A(_027_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _142_ (
    .A(_026_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _143_ (
    .A(_033_),
    .B(_030_),
    .Y(_000_[7])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _144_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _145_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _146_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _147_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _148_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _149_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _150_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _151_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _152_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(selector[0])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _153_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(selector[1])
  );
  (* src = "log_32_8Synth.v:11" *)
  DFF _154_ (
    .C(clk_4f),
    .D(_002_),
    .Q(valid_out)
  );
endmodule

(* top =  1  *)
(* src = "phytxSynth.v:5" *)
module phytxSynth(data_in, valid_in, reset, clk_f, clk_2f, clk_4f, clk_32f, data_out0, data_out1);
  (* src = "phytxSynth.v:11" *)
  wire [31:0] BS_out0;
  (* src = "phytxSynth.v:11" *)
  wire [31:0] BS_out1;
  (* src = "phytxSynth.v:12" *)
  wire BSvalid_out0;
  (* src = "phytxSynth.v:12" *)
  wire BSvalid_out1;
  (* src = "phytxSynth.v:14" *)
  wire [7:0] a328_out0;
  (* src = "phytxSynth.v:17" *)
  wire [7:0] a328_out1;
  (* src = "phytxSynth.v:15" *)
  wire a328valid_out0;
  (* src = "phytxSynth.v:18" *)
  wire a328valid_out1;
  (* src = "phytxSynth.v:7" *)
  input clk_2f;
  (* src = "phytxSynth.v:7" *)
  input clk_32f;
  (* src = "phytxSynth.v:7" *)
  input clk_4f;
  (* src = "phytxSynth.v:7" *)
  input clk_f;
  (* src = "phytxSynth.v:6" *)
  input [31:0] data_in;
  (* src = "phytxSynth.v:8" *)
  output data_out0;
  (* src = "phytxSynth.v:9" *)
  output data_out1;
  (* src = "phytxSynth.v:7" *)
  input reset;
  (* src = "phytxSynth.v:7" *)
  input valid_in;
  (* module_not_derived = 32'd1 *)
  (* src = "phytxSynth.v:21" *)
  bytestripingSynth BS (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_in(data_in),
    .lane_0(BS_out0),
    .lane_1(BS_out1),
    .reset(reset),
    .valid_in(valid_in),
    .valid_out0(BSvalid_out0),
    .valid_out1(BSvalid_out1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phytxSynth.v:33" *)
  log_32_8Synth a328bits0 (
    .clk_4f(clk_4f),
    .data_in(BS_out0),
    .data_out(a328_out0),
    .reset(reset),
    .valid(BSvalid_out0),
    .valid_out(a328valid_out0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phytxSynth.v:42" *)
  log_32_8Synth a328bits1 (
    .clk_4f(clk_4f),
    .data_in(BS_out1),
    .data_out(a328_out1),
    .reset(reset),
    .valid(BSvalid_out1),
    .valid_out(a328valid_out1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phytxSynth.v:51" *)
  Paralelo_SerialSynth paraleloserial0 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(a328_out0),
    .data_out(data_out0),
    .reset(reset),
    .valid_in(a328valid_out0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "phytxSynth.v:60" *)
  Paralelo_SerialSynth paraleloserial1 (
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_in(a328_out1),
    .data_out(data_out1),
    .reset(reset),
    .valid_in(a328valid_out1)
  );
endmodule
