/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "ser_par_sint.v:1" *)
module ser_par_sint(reset, clk_4f, clk_32f, data_in, active, valid_out, data_out);
  (* src = "ser_par_sint.v:43" *)
  wire [7:0] _000_;
  (* src = "ser_par_sint.v:24" *)
  wire [7:0] _001_;
  (* src = "ser_par_sint.v:24" *)
  wire [7:0] _002_;
  (* src = "ser_par_sint.v:24" *)
  wire [7:0] _003_;
  (* src = "ser_par_sint.v:43" *)
  wire [7:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  (* src = "ser_par_sint.v:6" *)
  wire [7:0] BC_counter;
  (* src = "ser_par_sint.v:3" *)
  output active;
  (* src = "ser_par_sint.v:2" *)
  input clk_32f;
  (* src = "ser_par_sint.v:2" *)
  input clk_4f;
  (* src = "ser_par_sint.v:6" *)
  wire [7:0] contador;
  (* src = "ser_par_sint.v:6" *)
  wire [7:0] data;
  (* src = "ser_par_sint.v:6" *)
  wire [7:0] data2send;
  (* src = "ser_par_sint.v:2" *)
  input data_in;
  (* src = "ser_par_sint.v:4" *)
  output [7:0] data_out;
  (* src = "ser_par_sint.v:2" *)
  input reset;
  (* src = "ser_par_sint.v:3" *)
  output valid_out;
  NOT _178_ (
    .A(data2send[0]),
    .Y(_163_)
  );
  NOT _179_ (
    .A(BC_counter[0]),
    .Y(_164_)
  );
  NOT _180_ (
    .A(BC_counter[3]),
    .Y(_165_)
  );
  NOT _181_ (
    .A(contador[3]),
    .Y(_166_)
  );
  NOT _182_ (
    .A(contador[1]),
    .Y(_167_)
  );
  NOT _183_ (
    .A(contador[0]),
    .Y(_168_)
  );
  NOT _184_ (
    .A(contador[2]),
    .Y(_169_)
  );
  NOT _185_ (
    .A(contador[4]),
    .Y(_170_)
  );
  NOT _186_ (
    .A(contador[5]),
    .Y(_171_)
  );
  NOT _187_ (
    .A(contador[6]),
    .Y(_172_)
  );
  NOT _188_ (
    .A(contador[7]),
    .Y(_173_)
  );
  NOT _189_ (
    .A(reset),
    .Y(_174_)
  );
  NOT _190_ (
    .A(data_in),
    .Y(_175_)
  );
  NOT _191_ (
    .A(data[7]),
    .Y(_176_)
  );
  NOT _192_ (
    .A(data[6]),
    .Y(_177_)
  );
  NOT _193_ (
    .A(data[5]),
    .Y(_005_)
  );
  NOT _194_ (
    .A(data[4]),
    .Y(_006_)
  );
  NOT _195_ (
    .A(data[3]),
    .Y(_007_)
  );
  NOT _196_ (
    .A(data[2]),
    .Y(_008_)
  );
  NOT _197_ (
    .A(data[1]),
    .Y(_009_)
  );
  NOT _198_ (
    .A(data[0]),
    .Y(_010_)
  );
  NOT _199_ (
    .A(data_out[2]),
    .Y(_011_)
  );
  NOR _200_ (
    .A(BC_counter[4]),
    .B(BC_counter[5]),
    .Y(_012_)
  );
  NOR _201_ (
    .A(BC_counter[6]),
    .B(BC_counter[7]),
    .Y(_013_)
  );
  NAND _202_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _203_ (
    .A(_165_),
    .B(BC_counter[2]),
    .Y(_015_)
  );
  NOT _204_ (
    .A(_015_),
    .Y(_016_)
  );
  NOR _205_ (
    .A(BC_counter[0]),
    .B(BC_counter[1]),
    .Y(_017_)
  );
  NAND _206_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _207_ (
    .A(_014_),
    .B(_018_),
    .Y(active)
  );
  NOT _208_ (
    .A(active),
    .Y(_019_)
  );
  NOR _209_ (
    .A(data2send[0]),
    .B(data2send[1]),
    .Y(_020_)
  );
  NOT _210_ (
    .A(_020_),
    .Y(_021_)
  );
  NOR _211_ (
    .A(data2send[6]),
    .B(BC_counter[3]),
    .Y(_022_)
  );
  NAND _212_ (
    .A(data2send[2]),
    .B(data2send[3]),
    .Y(_023_)
  );
  NOT _213_ (
    .A(_023_),
    .Y(_024_)
  );
  NAND _214_ (
    .A(_022_),
    .B(_024_),
    .Y(_025_)
  );
  NOR _215_ (
    .A(_021_),
    .B(_025_),
    .Y(_026_)
  );
  NAND _216_ (
    .A(data2send[4]),
    .B(data2send[5]),
    .Y(_027_)
  );
  NOT _217_ (
    .A(_027_),
    .Y(_028_)
  );
  NAND _218_ (
    .A(data2send[7]),
    .B(_028_),
    .Y(_029_)
  );
  NOR _219_ (
    .A(_014_),
    .B(_029_),
    .Y(_030_)
  );
  NAND _220_ (
    .A(_026_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _221_ (
    .A(BC_counter[3]),
    .B(_014_),
    .Y(_032_)
  );
  NOT _222_ (
    .A(_032_),
    .Y(_033_)
  );
  NAND _223_ (
    .A(data2send[3]),
    .B(data2send[7]),
    .Y(_034_)
  );
  NOR _224_ (
    .A(_027_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _225_ (
    .A(data2send[1]),
    .B(data2send[6]),
    .Y(_036_)
  );
  NOT _226_ (
    .A(_036_),
    .Y(_037_)
  );
  NAND _227_ (
    .A(_163_),
    .B(data2send[2]),
    .Y(_038_)
  );
  NOR _228_ (
    .A(_037_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _229_ (
    .A(_035_),
    .B(_039_),
    .Y(_040_)
  );
  NOR _230_ (
    .A(_033_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _231_ (
    .A(_015_),
    .B(_041_),
    .Y(_042_)
  );
  NAND _232_ (
    .A(_164_),
    .B(_042_),
    .Y(_043_)
  );
  NAND _233_ (
    .A(reset),
    .B(_043_),
    .Y(_044_)
  );
  NOR _234_ (
    .A(_164_),
    .B(_042_),
    .Y(_045_)
  );
  NOR _235_ (
    .A(_044_),
    .B(_045_),
    .Y(_000_[0])
  );
  NOR _236_ (
    .A(BC_counter[1]),
    .B(_045_),
    .Y(_046_)
  );
  NAND _237_ (
    .A(BC_counter[0]),
    .B(BC_counter[1]),
    .Y(_047_)
  );
  NOR _238_ (
    .A(_031_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _239_ (
    .A(_015_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _240_ (
    .A(reset),
    .B(_049_),
    .Y(_050_)
  );
  NOR _241_ (
    .A(_046_),
    .B(_050_),
    .Y(_000_[1])
  );
  NOR _242_ (
    .A(BC_counter[2]),
    .B(_048_),
    .Y(_051_)
  );
  NOR _243_ (
    .A(_174_),
    .B(_051_),
    .Y(_000_[2])
  );
  NAND _244_ (
    .A(BC_counter[3]),
    .B(reset),
    .Y(_052_)
  );
  NOT _245_ (
    .A(_052_),
    .Y(_000_[3])
  );
  NAND _246_ (
    .A(BC_counter[4]),
    .B(reset),
    .Y(_053_)
  );
  NOT _247_ (
    .A(_053_),
    .Y(_000_[4])
  );
  NAND _248_ (
    .A(BC_counter[5]),
    .B(reset),
    .Y(_054_)
  );
  NOT _249_ (
    .A(_054_),
    .Y(_000_[5])
  );
  NAND _250_ (
    .A(BC_counter[6]),
    .B(reset),
    .Y(_055_)
  );
  NOT _251_ (
    .A(_055_),
    .Y(_000_[6])
  );
  NAND _252_ (
    .A(BC_counter[7]),
    .B(reset),
    .Y(_056_)
  );
  NOT _253_ (
    .A(_056_),
    .Y(_000_[7])
  );
  NAND _254_ (
    .A(data2send[0]),
    .B(reset),
    .Y(_057_)
  );
  NOT _255_ (
    .A(_057_),
    .Y(_004_[0])
  );
  NAND _256_ (
    .A(data2send[1]),
    .B(reset),
    .Y(_058_)
  );
  NOT _257_ (
    .A(_058_),
    .Y(_004_[1])
  );
  NAND _258_ (
    .A(reset),
    .B(data2send[2]),
    .Y(_059_)
  );
  NOT _259_ (
    .A(_059_),
    .Y(_004_[2])
  );
  NAND _260_ (
    .A(reset),
    .B(data2send[3]),
    .Y(_060_)
  );
  NOT _261_ (
    .A(_060_),
    .Y(_004_[3])
  );
  NAND _262_ (
    .A(reset),
    .B(data2send[4]),
    .Y(_061_)
  );
  NOT _263_ (
    .A(_061_),
    .Y(_004_[4])
  );
  NAND _264_ (
    .A(reset),
    .B(data2send[5]),
    .Y(_062_)
  );
  NOT _265_ (
    .A(_062_),
    .Y(_004_[5])
  );
  NAND _266_ (
    .A(data2send[6]),
    .B(reset),
    .Y(_063_)
  );
  NOT _267_ (
    .A(_063_),
    .Y(_004_[6])
  );
  NAND _268_ (
    .A(reset),
    .B(data2send[7]),
    .Y(_064_)
  );
  NOT _269_ (
    .A(_064_),
    .Y(_004_[7])
  );
  NAND _270_ (
    .A(contador[1]),
    .B(contador[0]),
    .Y(_065_)
  );
  NOR _271_ (
    .A(contador[3]),
    .B(contador[4]),
    .Y(_066_)
  );
  NOT _272_ (
    .A(_066_),
    .Y(_067_)
  );
  NOR _273_ (
    .A(contador[5]),
    .B(contador[6]),
    .Y(_068_)
  );
  NAND _274_ (
    .A(_173_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _275_ (
    .A(_067_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _276_ (
    .A(contador[2]),
    .B(_070_),
    .Y(_071_)
  );
  NOR _277_ (
    .A(_065_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _278_ (
    .A(data[7]),
    .B(_072_),
    .Y(_073_)
  );
  NAND _279_ (
    .A(_175_),
    .B(_072_),
    .Y(_074_)
  );
  NAND _280_ (
    .A(reset),
    .B(_074_),
    .Y(_075_)
  );
  NOR _281_ (
    .A(_073_),
    .B(_075_),
    .Y(_003_[7])
  );
  NAND _282_ (
    .A(contador[1]),
    .B(_168_),
    .Y(_076_)
  );
  NOR _283_ (
    .A(_071_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _284_ (
    .A(data[6]),
    .B(_077_),
    .Y(_078_)
  );
  NAND _285_ (
    .A(_175_),
    .B(_077_),
    .Y(_079_)
  );
  NAND _286_ (
    .A(reset),
    .B(_079_),
    .Y(_080_)
  );
  NOR _287_ (
    .A(_078_),
    .B(_080_),
    .Y(_003_[6])
  );
  NAND _288_ (
    .A(_167_),
    .B(contador[0]),
    .Y(_081_)
  );
  NOR _289_ (
    .A(_071_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _290_ (
    .A(data[5]),
    .B(_082_),
    .Y(_083_)
  );
  NAND _291_ (
    .A(_175_),
    .B(_082_),
    .Y(_084_)
  );
  NAND _292_ (
    .A(reset),
    .B(_084_),
    .Y(_085_)
  );
  NOR _293_ (
    .A(_083_),
    .B(_085_),
    .Y(_003_[5])
  );
  NOR _294_ (
    .A(contador[1]),
    .B(contador[0]),
    .Y(_086_)
  );
  NAND _295_ (
    .A(_167_),
    .B(_168_),
    .Y(_087_)
  );
  NOR _296_ (
    .A(_071_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _297_ (
    .A(data[4]),
    .B(_088_),
    .Y(_089_)
  );
  NAND _298_ (
    .A(_175_),
    .B(_088_),
    .Y(_090_)
  );
  NAND _299_ (
    .A(reset),
    .B(_090_),
    .Y(_091_)
  );
  NOR _300_ (
    .A(_089_),
    .B(_091_),
    .Y(_003_[4])
  );
  NAND _301_ (
    .A(_169_),
    .B(_070_),
    .Y(_092_)
  );
  NOR _302_ (
    .A(_065_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _303_ (
    .A(data[3]),
    .B(_093_),
    .Y(_094_)
  );
  NAND _304_ (
    .A(_175_),
    .B(_093_),
    .Y(_095_)
  );
  NAND _305_ (
    .A(reset),
    .B(_095_),
    .Y(_096_)
  );
  NOR _306_ (
    .A(_094_),
    .B(_096_),
    .Y(_003_[3])
  );
  NOR _307_ (
    .A(_076_),
    .B(_092_),
    .Y(_097_)
  );
  NOR _308_ (
    .A(data[2]),
    .B(_097_),
    .Y(_098_)
  );
  NAND _309_ (
    .A(_175_),
    .B(_097_),
    .Y(_099_)
  );
  NAND _310_ (
    .A(reset),
    .B(_099_),
    .Y(_100_)
  );
  NOR _311_ (
    .A(_098_),
    .B(_100_),
    .Y(_003_[2])
  );
  NOR _312_ (
    .A(_081_),
    .B(_092_),
    .Y(_101_)
  );
  NOR _313_ (
    .A(data[1]),
    .B(_101_),
    .Y(_102_)
  );
  NAND _314_ (
    .A(_175_),
    .B(_101_),
    .Y(_103_)
  );
  NAND _315_ (
    .A(reset),
    .B(_103_),
    .Y(_104_)
  );
  NOR _316_ (
    .A(_102_),
    .B(_104_),
    .Y(_003_[1])
  );
  NOR _317_ (
    .A(contador[2]),
    .B(_087_),
    .Y(_105_)
  );
  NOT _318_ (
    .A(_105_),
    .Y(_106_)
  );
  NOR _319_ (
    .A(_087_),
    .B(_092_),
    .Y(_107_)
  );
  NAND _320_ (
    .A(_070_),
    .B(_105_),
    .Y(_108_)
  );
  NOR _321_ (
    .A(_175_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _322_ (
    .A(_010_),
    .B(_107_),
    .Y(_110_)
  );
  NOR _323_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _324_ (
    .A(_174_),
    .B(_111_),
    .Y(_003_[0])
  );
  NAND _325_ (
    .A(contador[0]),
    .B(reset),
    .Y(_001_[0])
  );
  NOR _326_ (
    .A(_174_),
    .B(_086_),
    .Y(_112_)
  );
  NAND _327_ (
    .A(_065_),
    .B(_112_),
    .Y(_001_[1])
  );
  NOR _328_ (
    .A(_169_),
    .B(_086_),
    .Y(_113_)
  );
  NOR _329_ (
    .A(_174_),
    .B(_113_),
    .Y(_114_)
  );
  NAND _330_ (
    .A(_106_),
    .B(_114_),
    .Y(_001_[2])
  );
  NOR _331_ (
    .A(contador[3]),
    .B(_106_),
    .Y(_115_)
  );
  NOR _332_ (
    .A(_166_),
    .B(_105_),
    .Y(_116_)
  );
  NOR _333_ (
    .A(_115_),
    .B(_116_),
    .Y(_117_)
  );
  NAND _334_ (
    .A(reset),
    .B(_108_),
    .Y(_118_)
  );
  NOR _335_ (
    .A(_117_),
    .B(_118_),
    .Y(_001_[3])
  );
  NOR _336_ (
    .A(_170_),
    .B(_115_),
    .Y(_119_)
  );
  NOR _337_ (
    .A(_067_),
    .B(_106_),
    .Y(_120_)
  );
  NAND _338_ (
    .A(_066_),
    .B(_105_),
    .Y(_121_)
  );
  NOR _339_ (
    .A(_119_),
    .B(_120_),
    .Y(_122_)
  );
  NOR _340_ (
    .A(_118_),
    .B(_122_),
    .Y(_001_[4])
  );
  NOR _341_ (
    .A(_171_),
    .B(_120_),
    .Y(_123_)
  );
  NOR _342_ (
    .A(contador[5]),
    .B(_121_),
    .Y(_124_)
  );
  NOT _343_ (
    .A(_124_),
    .Y(_125_)
  );
  NOR _344_ (
    .A(_123_),
    .B(_124_),
    .Y(_126_)
  );
  NOR _345_ (
    .A(_118_),
    .B(_126_),
    .Y(_001_[5])
  );
  NOR _346_ (
    .A(_172_),
    .B(_124_),
    .Y(_127_)
  );
  NOR _347_ (
    .A(contador[6]),
    .B(_125_),
    .Y(_128_)
  );
  NOR _348_ (
    .A(_127_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _349_ (
    .A(_118_),
    .B(_129_),
    .Y(_001_[6])
  );
  NAND _350_ (
    .A(contador[7]),
    .B(reset),
    .Y(_130_)
  );
  NOR _351_ (
    .A(_128_),
    .B(_130_),
    .Y(_001_[7])
  );
  NAND _352_ (
    .A(_010_),
    .B(_072_),
    .Y(_131_)
  );
  NAND _353_ (
    .A(reset),
    .B(_131_),
    .Y(_132_)
  );
  NOR _354_ (
    .A(data2send[0]),
    .B(_072_),
    .Y(_133_)
  );
  NOR _355_ (
    .A(_132_),
    .B(_133_),
    .Y(_002_[0])
  );
  NAND _356_ (
    .A(_009_),
    .B(_072_),
    .Y(_134_)
  );
  NAND _357_ (
    .A(reset),
    .B(_134_),
    .Y(_135_)
  );
  NOR _358_ (
    .A(data2send[1]),
    .B(_072_),
    .Y(_136_)
  );
  NOR _359_ (
    .A(_135_),
    .B(_136_),
    .Y(_002_[1])
  );
  NAND _360_ (
    .A(_008_),
    .B(_072_),
    .Y(_137_)
  );
  NAND _361_ (
    .A(reset),
    .B(_137_),
    .Y(_138_)
  );
  NOR _362_ (
    .A(data2send[2]),
    .B(_072_),
    .Y(_139_)
  );
  NOR _363_ (
    .A(_138_),
    .B(_139_),
    .Y(_002_[2])
  );
  NAND _364_ (
    .A(_007_),
    .B(_072_),
    .Y(_140_)
  );
  NAND _365_ (
    .A(reset),
    .B(_140_),
    .Y(_141_)
  );
  NOR _366_ (
    .A(data2send[3]),
    .B(_072_),
    .Y(_142_)
  );
  NOR _367_ (
    .A(_141_),
    .B(_142_),
    .Y(_002_[3])
  );
  NAND _368_ (
    .A(_006_),
    .B(_072_),
    .Y(_143_)
  );
  NAND _369_ (
    .A(reset),
    .B(_143_),
    .Y(_144_)
  );
  NOR _370_ (
    .A(data2send[4]),
    .B(_072_),
    .Y(_145_)
  );
  NOR _371_ (
    .A(_144_),
    .B(_145_),
    .Y(_002_[4])
  );
  NAND _372_ (
    .A(_005_),
    .B(_072_),
    .Y(_146_)
  );
  NAND _373_ (
    .A(reset),
    .B(_146_),
    .Y(_147_)
  );
  NOR _374_ (
    .A(data2send[5]),
    .B(_072_),
    .Y(_148_)
  );
  NOR _375_ (
    .A(_147_),
    .B(_148_),
    .Y(_002_[5])
  );
  NAND _376_ (
    .A(_177_),
    .B(_072_),
    .Y(_149_)
  );
  NAND _377_ (
    .A(reset),
    .B(_149_),
    .Y(_150_)
  );
  NOR _378_ (
    .A(data2send[6]),
    .B(_072_),
    .Y(_151_)
  );
  NOR _379_ (
    .A(_150_),
    .B(_151_),
    .Y(_002_[6])
  );
  NAND _380_ (
    .A(_176_),
    .B(_072_),
    .Y(_152_)
  );
  NAND _381_ (
    .A(reset),
    .B(_152_),
    .Y(_153_)
  );
  NOR _382_ (
    .A(data2send[7]),
    .B(_072_),
    .Y(_154_)
  );
  NOR _383_ (
    .A(_153_),
    .B(_154_),
    .Y(_002_[7])
  );
  NAND _384_ (
    .A(data_out[4]),
    .B(data_out[5]),
    .Y(_155_)
  );
  NOR _385_ (
    .A(data_out[6]),
    .B(_011_),
    .Y(_156_)
  );
  NAND _386_ (
    .A(data_out[3]),
    .B(data_out[7]),
    .Y(_157_)
  );
  NOR _387_ (
    .A(data_out[0]),
    .B(data_out[1]),
    .Y(_158_)
  );
  NOT _388_ (
    .A(_158_),
    .Y(_159_)
  );
  NOR _389_ (
    .A(_157_),
    .B(_159_),
    .Y(_160_)
  );
  NAND _390_ (
    .A(_156_),
    .B(_160_),
    .Y(_161_)
  );
  NOR _391_ (
    .A(_155_),
    .B(_161_),
    .Y(_162_)
  );
  NOR _392_ (
    .A(_019_),
    .B(_162_),
    .Y(valid_out)
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _393_ (
    .C(clk_4f),
    .D(_004_[0]),
    .Q(data_out[0])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _394_ (
    .C(clk_4f),
    .D(_004_[1]),
    .Q(data_out[1])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _395_ (
    .C(clk_4f),
    .D(_004_[2]),
    .Q(data_out[2])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _396_ (
    .C(clk_4f),
    .D(_004_[3]),
    .Q(data_out[3])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _397_ (
    .C(clk_4f),
    .D(_004_[4]),
    .Q(data_out[4])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _398_ (
    .C(clk_4f),
    .D(_004_[5]),
    .Q(data_out[5])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _399_ (
    .C(clk_4f),
    .D(_004_[6]),
    .Q(data_out[6])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _400_ (
    .C(clk_4f),
    .D(_004_[7]),
    .Q(data_out[7])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _401_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _402_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _403_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _404_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(BC_counter[3])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _405_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(BC_counter[4])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _406_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(BC_counter[5])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _407_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(BC_counter[6])
  );
  (* src = "ser_par_sint.v:43" *)
  DFF _408_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(BC_counter[7])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _409_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(data2send[0])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _410_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(data2send[1])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _411_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(data2send[2])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _412_ (
    .C(clk_32f),
    .D(_002_[3]),
    .Q(data2send[3])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _413_ (
    .C(clk_32f),
    .D(_002_[4]),
    .Q(data2send[4])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _414_ (
    .C(clk_32f),
    .D(_002_[5]),
    .Q(data2send[5])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _415_ (
    .C(clk_32f),
    .D(_002_[6]),
    .Q(data2send[6])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _416_ (
    .C(clk_32f),
    .D(_002_[7]),
    .Q(data2send[7])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _417_ (
    .C(clk_32f),
    .D(_001_[0]),
    .Q(contador[0])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _418_ (
    .C(clk_32f),
    .D(_001_[1]),
    .Q(contador[1])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _419_ (
    .C(clk_32f),
    .D(_001_[2]),
    .Q(contador[2])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _420_ (
    .C(clk_32f),
    .D(_001_[3]),
    .Q(contador[3])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _421_ (
    .C(clk_32f),
    .D(_001_[4]),
    .Q(contador[4])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _422_ (
    .C(clk_32f),
    .D(_001_[5]),
    .Q(contador[5])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _423_ (
    .C(clk_32f),
    .D(_001_[6]),
    .Q(contador[6])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _424_ (
    .C(clk_32f),
    .D(_001_[7]),
    .Q(contador[7])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _425_ (
    .C(clk_32f),
    .D(_003_[0]),
    .Q(data[0])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _426_ (
    .C(clk_32f),
    .D(_003_[1]),
    .Q(data[1])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _427_ (
    .C(clk_32f),
    .D(_003_[2]),
    .Q(data[2])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _428_ (
    .C(clk_32f),
    .D(_003_[3]),
    .Q(data[3])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _429_ (
    .C(clk_32f),
    .D(_003_[4]),
    .Q(data[4])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _430_ (
    .C(clk_32f),
    .D(_003_[5]),
    .Q(data[5])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _431_ (
    .C(clk_32f),
    .D(_003_[6]),
    .Q(data[6])
  );
  (* src = "ser_par_sint.v:24" *)
  DFF _432_ (
    .C(clk_32f),
    .D(_003_[7]),
    .Q(data[7])
  );
endmodule
