/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "un_byte_stripingS.v:1" *)
module un_byte_stripingS(data_out, reset_L, lane_0, lane_1, valid_0, valid_1, valid_out, clk_2f, clk_f);
  (* src = "un_byte_stripingS.v:19" *)
  wire [31:0] _000_;
  (* src = "un_byte_stripingS.v:19" *)
  wire _001_;
  (* src = "un_byte_stripingS.v:19" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  (* src = "un_byte_stripingS.v:9" *)
  input clk_2f;
  (* src = "un_byte_stripingS.v:10" *)
  input clk_f;
  (* src = "un_byte_stripingS.v:2" *)
  output [31:0] data_out;
  (* src = "un_byte_stripingS.v:4" *)
  input [31:0] lane_0;
  (* src = "un_byte_stripingS.v:5" *)
  input [31:0] lane_1;
  (* src = "un_byte_stripingS.v:3" *)
  input reset_L;
  (* src = "un_byte_stripingS.v:11" *)
  wire selector;
  (* src = "un_byte_stripingS.v:6" *)
  input valid_0;
  (* src = "un_byte_stripingS.v:7" *)
  input valid_1;
  (* src = "un_byte_stripingS.v:8" *)
  output valid_out;
  NOT _134_ (
    .A(lane_1[31]),
    .Y(_003_)
  );
  NOT _135_ (
    .A(selector),
    .Y(_004_)
  );
  NOT _136_ (
    .A(valid_0),
    .Y(_005_)
  );
  NOT _137_ (
    .A(lane_1[0]),
    .Y(_006_)
  );
  NOT _138_ (
    .A(lane_1[1]),
    .Y(_007_)
  );
  NOT _139_ (
    .A(lane_1[2]),
    .Y(_008_)
  );
  NOT _140_ (
    .A(lane_1[3]),
    .Y(_009_)
  );
  NOT _141_ (
    .A(lane_1[4]),
    .Y(_010_)
  );
  NOT _142_ (
    .A(lane_1[5]),
    .Y(_011_)
  );
  NOT _143_ (
    .A(lane_1[6]),
    .Y(_012_)
  );
  NOT _144_ (
    .A(lane_1[7]),
    .Y(_013_)
  );
  NOT _145_ (
    .A(lane_1[8]),
    .Y(_014_)
  );
  NOT _146_ (
    .A(lane_1[9]),
    .Y(_015_)
  );
  NOT _147_ (
    .A(lane_1[10]),
    .Y(_016_)
  );
  NOT _148_ (
    .A(lane_1[11]),
    .Y(_017_)
  );
  NOT _149_ (
    .A(lane_1[12]),
    .Y(_018_)
  );
  NOT _150_ (
    .A(lane_1[13]),
    .Y(_019_)
  );
  NOT _151_ (
    .A(lane_1[14]),
    .Y(_020_)
  );
  NOT _152_ (
    .A(lane_1[15]),
    .Y(_021_)
  );
  NOT _153_ (
    .A(lane_1[16]),
    .Y(_022_)
  );
  NOT _154_ (
    .A(lane_1[17]),
    .Y(_023_)
  );
  NOT _155_ (
    .A(lane_1[18]),
    .Y(_024_)
  );
  NOT _156_ (
    .A(lane_1[19]),
    .Y(_025_)
  );
  NOT _157_ (
    .A(lane_1[20]),
    .Y(_026_)
  );
  NOT _158_ (
    .A(lane_1[21]),
    .Y(_027_)
  );
  NOT _159_ (
    .A(lane_1[22]),
    .Y(_028_)
  );
  NOT _160_ (
    .A(lane_1[23]),
    .Y(_029_)
  );
  NOT _161_ (
    .A(lane_1[24]),
    .Y(_030_)
  );
  NOT _162_ (
    .A(lane_1[25]),
    .Y(_031_)
  );
  NOT _163_ (
    .A(lane_1[26]),
    .Y(_032_)
  );
  NOT _164_ (
    .A(lane_1[27]),
    .Y(_033_)
  );
  NOT _165_ (
    .A(lane_1[28]),
    .Y(_034_)
  );
  NOT _166_ (
    .A(lane_1[29]),
    .Y(_035_)
  );
  NOT _167_ (
    .A(lane_1[30]),
    .Y(_036_)
  );
  NOR _168_ (
    .A(selector),
    .B(lane_0[0]),
    .Y(_037_)
  );
  NOR _169_ (
    .A(selector),
    .B(_005_),
    .Y(_001_)
  );
  NAND _170_ (
    .A(selector),
    .B(_006_),
    .Y(_038_)
  );
  NAND _171_ (
    .A(valid_0),
    .B(_038_),
    .Y(_039_)
  );
  NOR _172_ (
    .A(_037_),
    .B(_039_),
    .Y(_000_[0])
  );
  NOR _173_ (
    .A(selector),
    .B(lane_0[1]),
    .Y(_040_)
  );
  NAND _174_ (
    .A(selector),
    .B(_007_),
    .Y(_041_)
  );
  NAND _175_ (
    .A(valid_0),
    .B(_041_),
    .Y(_042_)
  );
  NOR _176_ (
    .A(_040_),
    .B(_042_),
    .Y(_000_[1])
  );
  NOR _177_ (
    .A(selector),
    .B(lane_0[2]),
    .Y(_043_)
  );
  NAND _178_ (
    .A(selector),
    .B(_008_),
    .Y(_044_)
  );
  NAND _179_ (
    .A(valid_0),
    .B(_044_),
    .Y(_045_)
  );
  NOR _180_ (
    .A(_043_),
    .B(_045_),
    .Y(_000_[2])
  );
  NOR _181_ (
    .A(selector),
    .B(lane_0[3]),
    .Y(_046_)
  );
  NAND _182_ (
    .A(selector),
    .B(_009_),
    .Y(_047_)
  );
  NAND _183_ (
    .A(valid_0),
    .B(_047_),
    .Y(_048_)
  );
  NOR _184_ (
    .A(_046_),
    .B(_048_),
    .Y(_000_[3])
  );
  NOR _185_ (
    .A(selector),
    .B(lane_0[4]),
    .Y(_049_)
  );
  NAND _186_ (
    .A(selector),
    .B(_010_),
    .Y(_050_)
  );
  NAND _187_ (
    .A(valid_0),
    .B(_050_),
    .Y(_051_)
  );
  NOR _188_ (
    .A(_049_),
    .B(_051_),
    .Y(_000_[4])
  );
  NOR _189_ (
    .A(selector),
    .B(lane_0[5]),
    .Y(_052_)
  );
  NAND _190_ (
    .A(selector),
    .B(_011_),
    .Y(_053_)
  );
  NAND _191_ (
    .A(valid_0),
    .B(_053_),
    .Y(_054_)
  );
  NOR _192_ (
    .A(_052_),
    .B(_054_),
    .Y(_000_[5])
  );
  NOR _193_ (
    .A(selector),
    .B(lane_0[6]),
    .Y(_055_)
  );
  NAND _194_ (
    .A(selector),
    .B(_012_),
    .Y(_056_)
  );
  NAND _195_ (
    .A(valid_0),
    .B(_056_),
    .Y(_057_)
  );
  NOR _196_ (
    .A(_055_),
    .B(_057_),
    .Y(_000_[6])
  );
  NOR _197_ (
    .A(selector),
    .B(lane_0[7]),
    .Y(_058_)
  );
  NAND _198_ (
    .A(selector),
    .B(_013_),
    .Y(_059_)
  );
  NAND _199_ (
    .A(valid_0),
    .B(_059_),
    .Y(_060_)
  );
  NOR _200_ (
    .A(_058_),
    .B(_060_),
    .Y(_000_[7])
  );
  NOR _201_ (
    .A(selector),
    .B(lane_0[8]),
    .Y(_061_)
  );
  NAND _202_ (
    .A(selector),
    .B(_014_),
    .Y(_062_)
  );
  NAND _203_ (
    .A(valid_0),
    .B(_062_),
    .Y(_063_)
  );
  NOR _204_ (
    .A(_061_),
    .B(_063_),
    .Y(_000_[8])
  );
  NOR _205_ (
    .A(selector),
    .B(lane_0[9]),
    .Y(_064_)
  );
  NAND _206_ (
    .A(selector),
    .B(_015_),
    .Y(_065_)
  );
  NAND _207_ (
    .A(valid_0),
    .B(_065_),
    .Y(_066_)
  );
  NOR _208_ (
    .A(_064_),
    .B(_066_),
    .Y(_000_[9])
  );
  NOR _209_ (
    .A(selector),
    .B(lane_0[10]),
    .Y(_067_)
  );
  NAND _210_ (
    .A(selector),
    .B(_016_),
    .Y(_068_)
  );
  NAND _211_ (
    .A(valid_0),
    .B(_068_),
    .Y(_069_)
  );
  NOR _212_ (
    .A(_067_),
    .B(_069_),
    .Y(_000_[10])
  );
  NOR _213_ (
    .A(selector),
    .B(lane_0[11]),
    .Y(_070_)
  );
  NAND _214_ (
    .A(selector),
    .B(_017_),
    .Y(_071_)
  );
  NAND _215_ (
    .A(valid_0),
    .B(_071_),
    .Y(_072_)
  );
  NOR _216_ (
    .A(_070_),
    .B(_072_),
    .Y(_000_[11])
  );
  NOR _217_ (
    .A(selector),
    .B(lane_0[12]),
    .Y(_073_)
  );
  NAND _218_ (
    .A(selector),
    .B(_018_),
    .Y(_074_)
  );
  NAND _219_ (
    .A(valid_0),
    .B(_074_),
    .Y(_075_)
  );
  NOR _220_ (
    .A(_073_),
    .B(_075_),
    .Y(_000_[12])
  );
  NOR _221_ (
    .A(selector),
    .B(lane_0[13]),
    .Y(_076_)
  );
  NAND _222_ (
    .A(selector),
    .B(_019_),
    .Y(_077_)
  );
  NAND _223_ (
    .A(valid_0),
    .B(_077_),
    .Y(_078_)
  );
  NOR _224_ (
    .A(_076_),
    .B(_078_),
    .Y(_000_[13])
  );
  NOR _225_ (
    .A(selector),
    .B(lane_0[14]),
    .Y(_079_)
  );
  NAND _226_ (
    .A(selector),
    .B(_020_),
    .Y(_080_)
  );
  NAND _227_ (
    .A(valid_0),
    .B(_080_),
    .Y(_081_)
  );
  NOR _228_ (
    .A(_079_),
    .B(_081_),
    .Y(_000_[14])
  );
  NOR _229_ (
    .A(selector),
    .B(lane_0[15]),
    .Y(_082_)
  );
  NAND _230_ (
    .A(selector),
    .B(_021_),
    .Y(_083_)
  );
  NAND _231_ (
    .A(valid_0),
    .B(_083_),
    .Y(_084_)
  );
  NOR _232_ (
    .A(_082_),
    .B(_084_),
    .Y(_000_[15])
  );
  NOR _233_ (
    .A(selector),
    .B(lane_0[16]),
    .Y(_085_)
  );
  NAND _234_ (
    .A(selector),
    .B(_022_),
    .Y(_086_)
  );
  NAND _235_ (
    .A(valid_0),
    .B(_086_),
    .Y(_087_)
  );
  NOR _236_ (
    .A(_085_),
    .B(_087_),
    .Y(_000_[16])
  );
  NOR _237_ (
    .A(selector),
    .B(lane_0[17]),
    .Y(_088_)
  );
  NAND _238_ (
    .A(selector),
    .B(_023_),
    .Y(_089_)
  );
  NAND _239_ (
    .A(valid_0),
    .B(_089_),
    .Y(_090_)
  );
  NOR _240_ (
    .A(_088_),
    .B(_090_),
    .Y(_000_[17])
  );
  NOR _241_ (
    .A(selector),
    .B(lane_0[18]),
    .Y(_091_)
  );
  NAND _242_ (
    .A(selector),
    .B(_024_),
    .Y(_092_)
  );
  NAND _243_ (
    .A(valid_0),
    .B(_092_),
    .Y(_093_)
  );
  NOR _244_ (
    .A(_091_),
    .B(_093_),
    .Y(_000_[18])
  );
  NOR _245_ (
    .A(selector),
    .B(lane_0[19]),
    .Y(_094_)
  );
  NAND _246_ (
    .A(selector),
    .B(_025_),
    .Y(_095_)
  );
  NAND _247_ (
    .A(valid_0),
    .B(_095_),
    .Y(_096_)
  );
  NOR _248_ (
    .A(_094_),
    .B(_096_),
    .Y(_000_[19])
  );
  NOR _249_ (
    .A(selector),
    .B(lane_0[20]),
    .Y(_097_)
  );
  NAND _250_ (
    .A(selector),
    .B(_026_),
    .Y(_098_)
  );
  NAND _251_ (
    .A(valid_0),
    .B(_098_),
    .Y(_099_)
  );
  NOR _252_ (
    .A(_097_),
    .B(_099_),
    .Y(_000_[20])
  );
  NOR _253_ (
    .A(selector),
    .B(lane_0[21]),
    .Y(_100_)
  );
  NAND _254_ (
    .A(selector),
    .B(_027_),
    .Y(_101_)
  );
  NAND _255_ (
    .A(valid_0),
    .B(_101_),
    .Y(_102_)
  );
  NOR _256_ (
    .A(_100_),
    .B(_102_),
    .Y(_000_[21])
  );
  NOR _257_ (
    .A(selector),
    .B(lane_0[22]),
    .Y(_103_)
  );
  NAND _258_ (
    .A(selector),
    .B(_028_),
    .Y(_104_)
  );
  NAND _259_ (
    .A(valid_0),
    .B(_104_),
    .Y(_105_)
  );
  NOR _260_ (
    .A(_103_),
    .B(_105_),
    .Y(_000_[22])
  );
  NOR _261_ (
    .A(selector),
    .B(lane_0[23]),
    .Y(_106_)
  );
  NAND _262_ (
    .A(selector),
    .B(_029_),
    .Y(_107_)
  );
  NAND _263_ (
    .A(valid_0),
    .B(_107_),
    .Y(_108_)
  );
  NOR _264_ (
    .A(_106_),
    .B(_108_),
    .Y(_000_[23])
  );
  NOR _265_ (
    .A(selector),
    .B(lane_0[24]),
    .Y(_109_)
  );
  NAND _266_ (
    .A(selector),
    .B(_030_),
    .Y(_110_)
  );
  NAND _267_ (
    .A(valid_0),
    .B(_110_),
    .Y(_111_)
  );
  NOR _268_ (
    .A(_109_),
    .B(_111_),
    .Y(_000_[24])
  );
  NOR _269_ (
    .A(selector),
    .B(lane_0[25]),
    .Y(_112_)
  );
  NAND _270_ (
    .A(selector),
    .B(_031_),
    .Y(_113_)
  );
  NAND _271_ (
    .A(valid_0),
    .B(_113_),
    .Y(_114_)
  );
  NOR _272_ (
    .A(_112_),
    .B(_114_),
    .Y(_000_[25])
  );
  NOR _273_ (
    .A(selector),
    .B(lane_0[26]),
    .Y(_115_)
  );
  NAND _274_ (
    .A(selector),
    .B(_032_),
    .Y(_116_)
  );
  NAND _275_ (
    .A(valid_0),
    .B(_116_),
    .Y(_117_)
  );
  NOR _276_ (
    .A(_115_),
    .B(_117_),
    .Y(_000_[26])
  );
  NOR _277_ (
    .A(selector),
    .B(lane_0[27]),
    .Y(_118_)
  );
  NAND _278_ (
    .A(selector),
    .B(_033_),
    .Y(_119_)
  );
  NAND _279_ (
    .A(valid_0),
    .B(_119_),
    .Y(_120_)
  );
  NOR _280_ (
    .A(_118_),
    .B(_120_),
    .Y(_000_[27])
  );
  NOR _281_ (
    .A(selector),
    .B(lane_0[28]),
    .Y(_121_)
  );
  NAND _282_ (
    .A(selector),
    .B(_034_),
    .Y(_122_)
  );
  NAND _283_ (
    .A(valid_0),
    .B(_122_),
    .Y(_123_)
  );
  NOR _284_ (
    .A(_121_),
    .B(_123_),
    .Y(_000_[28])
  );
  NOR _285_ (
    .A(selector),
    .B(lane_0[29]),
    .Y(_124_)
  );
  NAND _286_ (
    .A(selector),
    .B(_035_),
    .Y(_125_)
  );
  NAND _287_ (
    .A(valid_0),
    .B(_125_),
    .Y(_126_)
  );
  NOR _288_ (
    .A(_124_),
    .B(_126_),
    .Y(_000_[29])
  );
  NOR _289_ (
    .A(selector),
    .B(lane_0[30]),
    .Y(_127_)
  );
  NAND _290_ (
    .A(selector),
    .B(_036_),
    .Y(_128_)
  );
  NAND _291_ (
    .A(valid_0),
    .B(_128_),
    .Y(_129_)
  );
  NOR _292_ (
    .A(_127_),
    .B(_129_),
    .Y(_000_[30])
  );
  NOR _293_ (
    .A(lane_0[31]),
    .B(selector),
    .Y(_130_)
  );
  NAND _294_ (
    .A(_003_),
    .B(selector),
    .Y(_131_)
  );
  NAND _295_ (
    .A(valid_0),
    .B(_131_),
    .Y(_132_)
  );
  NOR _296_ (
    .A(_130_),
    .B(_132_),
    .Y(_000_[31])
  );
  NOR _297_ (
    .A(_004_),
    .B(valid_1),
    .Y(_133_)
  );
  NOR _298_ (
    .A(_005_),
    .B(_133_),
    .Y(_002_)
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _299_ (
    .C(clk_2f),
    .D(_002_),
    .Q(valid_out)
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _300_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_out[0])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _301_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_out[1])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _302_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_out[2])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _303_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_out[3])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _304_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_out[4])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _305_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_out[5])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _306_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_out[6])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _307_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_out[7])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _308_ (
    .C(clk_2f),
    .D(_000_[8]),
    .Q(data_out[8])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _309_ (
    .C(clk_2f),
    .D(_000_[9]),
    .Q(data_out[9])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _310_ (
    .C(clk_2f),
    .D(_000_[10]),
    .Q(data_out[10])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _311_ (
    .C(clk_2f),
    .D(_000_[11]),
    .Q(data_out[11])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _312_ (
    .C(clk_2f),
    .D(_000_[12]),
    .Q(data_out[12])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _313_ (
    .C(clk_2f),
    .D(_000_[13]),
    .Q(data_out[13])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _314_ (
    .C(clk_2f),
    .D(_000_[14]),
    .Q(data_out[14])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _315_ (
    .C(clk_2f),
    .D(_000_[15]),
    .Q(data_out[15])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _316_ (
    .C(clk_2f),
    .D(_000_[16]),
    .Q(data_out[16])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _317_ (
    .C(clk_2f),
    .D(_000_[17]),
    .Q(data_out[17])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _318_ (
    .C(clk_2f),
    .D(_000_[18]),
    .Q(data_out[18])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _319_ (
    .C(clk_2f),
    .D(_000_[19]),
    .Q(data_out[19])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _320_ (
    .C(clk_2f),
    .D(_000_[20]),
    .Q(data_out[20])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _321_ (
    .C(clk_2f),
    .D(_000_[21]),
    .Q(data_out[21])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _322_ (
    .C(clk_2f),
    .D(_000_[22]),
    .Q(data_out[22])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _323_ (
    .C(clk_2f),
    .D(_000_[23]),
    .Q(data_out[23])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _324_ (
    .C(clk_2f),
    .D(_000_[24]),
    .Q(data_out[24])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _325_ (
    .C(clk_2f),
    .D(_000_[25]),
    .Q(data_out[25])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _326_ (
    .C(clk_2f),
    .D(_000_[26]),
    .Q(data_out[26])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _327_ (
    .C(clk_2f),
    .D(_000_[27]),
    .Q(data_out[27])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _328_ (
    .C(clk_2f),
    .D(_000_[28]),
    .Q(data_out[28])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _329_ (
    .C(clk_2f),
    .D(_000_[29]),
    .Q(data_out[29])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _330_ (
    .C(clk_2f),
    .D(_000_[30]),
    .Q(data_out[30])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _331_ (
    .C(clk_2f),
    .D(_000_[31]),
    .Q(data_out[31])
  );
  (* src = "un_byte_stripingS.v:19" *)
  DFF _332_ (
    .C(clk_2f),
    .D(_001_),
    .Q(selector)
  );
endmodule
